// Generated by Haxe 4.3.7
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Game extends haxe.lang.HxObject
{
	public Game(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Game()
	{
		//line 25 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.__hx_ctor__Game(this);
	}
	
	
	protected static void __hx_ctor__Game(haxe.root.Game __hx_this)
	{
	}
	
	
	public static int Health;
	
	public static java.lang.String Sickness;
	
	public static int Energy;
	
	public static int SicknessLevel;
	
	public static int Happiness;
	
	public static void loop()
	{
		//line 1 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\?"
		while (true)
		{
			//line 31 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
			{
				//line 33 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (( haxe.root.Game.Health > 100 )) 
				{
					//line 34 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Game.Health = 100;
				}
				else
				{
					//line 36 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					if (( haxe.root.Game.Health < 0 )) 
					{
						//line 37 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.Health = 0;
					}
					
				}
				
				//line 41 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (( haxe.root.Game.SicknessLevel > 100 )) 
				{
					//line 42 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Game.SicknessLevel = 100;
				}
				else
				{
					//line 44 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					if (( haxe.root.Game.SicknessLevel < 0 )) 
					{
						//line 45 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.SicknessLevel = 0;
					}
					
				}
				
				//line 49 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (( haxe.root.Game.Energy > 100 )) 
				{
					//line 50 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Game.Energy = 100;
				}
				else
				{
					//line 52 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					if (( haxe.root.Game.Energy < 0 )) 
					{
						//line 53 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.Energy = 0;
					}
					
				}
				
				//line 57 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (( haxe.root.Game.Happiness > 100 )) 
				{
					//line 58 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Game.Happiness = 100;
				}
				else
				{
					//line 60 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					if (( haxe.root.Game.Happiness < 0 )) 
					{
						//line 61 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.Happiness = 0;
					}
					
				}
				
				//line 64 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				java.lang.System.out.print(((java.lang.Object) (( ( ( ( ( ( ( ( ( ( ( ( "\n======= Cold Simulater =======\n1. Sleep (Decreases Sickness & increases Health)\n2. Learn Html&CSS (50% Chance to Decrease/increase Sickness)\n3. Sickness Meds (Your " + haxe.root.Game.Sickness ) + " Will Feel Slightly Better, But It Baste Bad [-Happiness]\n4. Exit\n\nSickness Type [" ) + haxe.root.Game.Sickness ) + "]\nSickness Level [" ) + haxe.root.Game.SicknessLevel ) + "%]\nhappiness [" ) + haxe.root.Game.Happiness ) + "%]\nHealth [" ) + haxe.root.Game.Health ) + "%]\nEnergy [" ) + haxe.root.Game.Energy ) + "]\n\n" )) ));
				//line 77 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				java.lang.System.out.print(((java.lang.Object) ("Option > ") ));
				//line 78 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				java.lang.String poption = haxe.root.Sys.stdin().readLine();
				//line 79 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				java.lang.String option = ((java.lang.String) (((java.lang.Object) (poption) )) ).trim();
				//line 81 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (( haxe.root.Game.Health == 0 )) 
				{
					//line 81 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Game.Passout();
				}
				
				//line 82 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (( haxe.root.Game.SicknessLevel <= 50 )) 
				{
					//line 82 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Game.Rested();
				}
				
				//line 84 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (haxe.lang.Runtime.valEq(option, "1")) 
				{
					//line 85 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					if (( haxe.root.Game.Energy < 75 )) 
					{
						//line 86 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.Log.trace.__hx_invoke2_o(0.0, "Sleeping", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (86) )) )}));
						//line 87 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.Log.trace.__hx_invoke2_o(0.0, "You Feel Well Rested", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (87) )) )}));
						//line 88 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Sys.sleep(0.3);
						//line 89 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						java.lang.System.out.println(((java.lang.Object) ("\n") ));
						//line 91 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						int HealthRestore = ((int) (( java.lang.Math.random() * 15 )) );
						//line 92 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.Health = ((int) (( ((int) (haxe.root.Game.Health) ) + HealthRestore )) );
						//line 93 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.SicknessLevel = ((int) (( ((int) (haxe.root.Game.SicknessLevel) ) - HealthRestore )) );
						//line 94 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.loop();
					}
					
					//line 96 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					if (( haxe.root.Game.Energy > 75 )) 
					{
						//line 97 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.Log.trace.__hx_invoke2_o(0.0, "Your Not Tired Enough", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (97) )) )}));
						//line 98 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Sys.sleep(0.9);
						//line 99 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.loop();
					}
					
				}
				else
				{
					//line 101 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					if (haxe.lang.Runtime.valEq(option, "2")) 
					{
						//line 103 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						int Chance = ((int) (( java.lang.Math.random() * 2 )) );
						//line 104 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.Log.trace.__hx_invoke2_o(0.0, ( ( "Chance [" + Chance ) + "]" ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (104) )) )}));
						//line 105 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						switch (Chance)
						{
							case 1:
							{
								//line 106 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								haxe.root.Game.Increase();
								//line 106 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								break;
							}
							
							
							case 2:
							{
								//line 107 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								haxe.root.Game.Decrease();
								//line 107 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								break;
							}
							
							
							default:
							{
								//line 108 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								haxe.root.Game.Increase();
								//line 108 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								break;
							}
							
						}
						
					}
					else
					{
						//line 110 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						if (haxe.lang.Runtime.valEq(option, "3")) 
						{
							//line 111 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
							if (( haxe.root.Game.Happiness > 60 )) 
							{
								//line 112 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								haxe.Log.trace.__hx_invoke2_o(0.0, ( ( "You took some pain meds, your " + haxe.root.Game.Sickness ) + " went down a little" ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (112) )) )}));
								//line 113 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								haxe.root.Game.SicknessLevel = ((int) (( ((int) (haxe.root.Game.SicknessLevel) ) - 8 )) );
								//line 114 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								haxe.root.Sys.sleep(0.8);
								//line 115 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								java.lang.System.out.println(((java.lang.Object) ("\n") ));
								//line 116 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								haxe.root.Game.loop();
							}
							else
							{
								//line 118 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
								if (( haxe.root.Game.Happiness < 60 )) 
								{
									//line 119 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
									haxe.Log.trace.__hx_invoke2_o(0.0, "The Pills taste To bad, You Dont Want To Take Them", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (119) )) )}));
									//line 120 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
									haxe.root.Sys.sleep(0.8);
									//line 121 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
									java.lang.System.out.println(((java.lang.Object) ("\n") ));
									//line 122 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
									haxe.root.Game.loop();
								}
								
							}
							
						}
						
					}
					
				}
				
				//line 124 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (haxe.lang.Runtime.valEq(option, "4")) 
				{
					//line 125 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.Log.trace.__hx_invoke2_o(0.0, "Ill cya bro <3", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (125) )) )}));
					//line 126 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Sys.exit(0);
				}
				else
				{
					//line 128 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.Log.trace.__hx_invoke2_o(0.0, "Please Enter A Valid Option", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (128) )) )}));
					//line 129 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Sys.sleep(0.4);
					//line 130 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.Log.trace.__hx_invoke2_o(0.0, "\n", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "loop"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (130) )) )}));
					//line 1 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\?"
					continue;
				}
				
			}
			
			//line 1 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\?"
			return ;
		}
		
	}
	
	
	public static void Increase()
	{
		//line 135 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		java.lang.System.out.println(((java.lang.Object) ("You Feel A Lot Worse, But At Least You Learned How To Center A Div!") ));
		//line 137 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int SChance = ((int) (( java.lang.Math.random() * 15 )) );
		//line 138 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.SicknessLevel = ((int) (( ((int) (haxe.root.Game.SicknessLevel) ) + SChance )) );
		//line 141 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int EChance = ((int) (( java.lang.Math.random() * 15 )) );
		//line 142 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Energy = ((int) (( ((int) (haxe.root.Game.Energy) ) - EChance )) );
		//line 145 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int HChance = ((int) (( java.lang.Math.random() * 15 )) );
		//line 146 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Health = ((int) (( ((int) (haxe.root.Game.Health) ) - HChance )) );
		//line 149 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int HPChance = ((int) (( java.lang.Math.random() * 15 )) );
		//line 150 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Happiness = ((int) (( ((int) (haxe.root.Game.Happiness) ) + HPChance )) );
		//line 151 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		java.lang.System.out.println(((java.lang.Object) ("\n") ));
		//line 152 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Sys.sleep(0.8);
		//line 153 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.loop();
	}
	
	
	public static void Decrease()
	{
		//line 157 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		java.lang.System.out.println(((java.lang.Object) ("You Feel A Lot Better, And You Also Learned How To Change Text Color With Inline CSS!") ));
		//line 159 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int SChance = ((int) (( java.lang.Math.random() * 15 )) );
		//line 160 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.SicknessLevel = ((int) (( ((int) (haxe.root.Game.SicknessLevel) ) - SChance )) );
		//line 163 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int EChance = ((int) (( java.lang.Math.random() * 15 )) );
		//line 164 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Energy = ((int) (( ((int) (haxe.root.Game.Energy) ) + EChance )) );
		//line 167 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int HChance = ((int) (( java.lang.Math.random() * 15 )) );
		//line 168 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Health = ((int) (( ((int) (haxe.root.Game.Health) ) + HChance )) );
		//line 171 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int HPChance = ((int) (( java.lang.Math.random() * 15 )) );
		//line 172 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Happiness = ((int) (( ((int) (haxe.root.Game.Happiness) ) + HPChance )) );
		//line 173 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		java.lang.System.out.println(((java.lang.Object) ("\n") ));
		//line 174 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Sys.sleep(0.8);
		//line 175 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.loop();
	}
	
	
	public static void Passout()
	{
		//line 178 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		java.lang.System.out.println(((java.lang.Object) ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n") ));
		//line 179 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, ( "You pass out in the kitchen from your " + haxe.root.Game.Sickness ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "Passout"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (179) )) )}));
		//line 180 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Ending Finished: [Fainted]", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "Passout"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (180) )) )}));
		//line 181 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Sys.sleep(0.7);
		//line 182 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Cold Sumulater Ending...", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "Passout"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (182) )) )}));
		//line 183 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Sys.sleep(((double) (1) ));
		//line 184 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Sys.exit(0);
	}
	
	
	public static void Rested()
	{
		//line 188 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		java.lang.System.out.println(((java.lang.Object) ("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n") ));
		//line 189 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, ( ( "You Wake Up And You Dont Feel Your " + haxe.root.Game.Sickness ) + " symptoms Anymore" ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "Rested"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (189) )) )}));
		//line 190 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Ending Finished: [Cured]", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "Rested"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (190) )) )}));
		//line 191 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Thx For Playing This Long :>", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "Rested"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (191) )) )}));
		//line 192 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Cold Sumulater Ending...", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Game", "src/Main.hx", "Rested"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (192) )) )}));
		//line 193 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Sys.sleep(0.9);
		//line 194 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Sys.exit(0);
	}
	
	
}


