// Generated by Haxe 4.3.7
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Main extends haxe.lang.HxObject
{
	public static void main(String[] args)
	{
		haxe.java.Init.init();
		haxe.root.Main.main();
	}
	
	public Main(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Main()
	{
		//line 3 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Main.__hx_ctor__Main(this);
	}
	
	
	protected static void __hx_ctor__Main(haxe.root.Main __hx_this)
	{
	}
	
	
	public static void main()
	{
		//line 5 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Hello, world!", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "src/Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (5) )) )}));
		//line 6 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Health = 100;
		//line 7 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.SicknessLevel = 100;
		//line 8 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Energy = 100;
		//line 9 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.Happiness = 70;
		//line 11 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		int Sick = ((int) (( java.lang.Math.random() * 3 )) );
		//line 12 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, ( "Output : " + Sick ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "src/Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (12) )) )}));
		//line 13 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		if (( Sick == 1 )) 
		{
			//line 14 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
			haxe.root.Game.Sickness = "Common Cold";
		}
		else
		{
			//line 15 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
			if (( Sick == 2 )) 
			{
				//line 16 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				haxe.root.Game.Sickness = "Fever";
			}
			else
			{
				//line 17 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
				if (( Sick == 3 )) 
				{
					//line 18 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					haxe.root.Game.Sickness = "Stressed";
				}
				else
				{
					//line 19 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
					if (( haxe.root.Game.Sickness == null )) 
					{
						//line 20 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
						haxe.root.Game.Sickness = "Common Cold";
					}
					
				}
				
			}
			
		}
		
		//line 22 "C:\\Users\\aceb0\\IdeaProjects\\untitled32\\src\\Main.hx"
		haxe.root.Game.loop();
	}
	
	
}


