// Generated by Haxe 4.3.7
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class Sys extends haxe.lang.HxObject
{
	public Sys(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public Sys()
	{
		//line 30 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\Sys.hx"
		haxe.root.Sys.__hx_ctor__Sys(this);
	}
	
	
	protected static void __hx_ctor__Sys(haxe.root.Sys __hx_this)
	{
	}
	
	
	public static void sleep(double seconds)
	{
		//line 70 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\Sys.hx"
		try 
		{
			//line 70 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\Sys.hx"
			java.lang.Thread.sleep(((long) (( seconds * 1000 )) ));
		}
		catch (java.lang.Throwable _g)
		{
			//line 72 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\Sys.hx"
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(((java.lang.Object) (haxe.Exception.caught(_g).unwrap()) ))) );
		}
		
		
	}
	
	
	public static void exit(int code)
	{
		//line 129 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\Sys.hx"
		java.lang.System.exit(((int) (code) ));
	}
	
	
	public static haxe.io.Input stdin()
	{
		//line 155 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\Sys.hx"
		java.io.InputStream _in = ((java.io.InputStream) (haxe.lang.Runtime.getField(java.lang.System.class, "in", false)) );
		//line 156 "C:\\HaxeToolkit\\haxe\\std\\java\\_std\\Sys.hx"
		return new haxe.java.io.NativeInput(((java.io.InputStream) (_in) ));
	}
	
	
}


